// <auto-generated />
using JuniorTennis.Infrastructure.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace include_sample.Migrations
{
    [DbContext(typeof(SampleDbContext))]
    [Migration("20210920080320_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("include_sample.Models.FirstLayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.HasKey("Id");

                    b.ToTable("first_layers");
                });

            modelBuilder.Entity("include_sample.Models.SecondLayerA", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("FirstLayerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FirstLayerId");

                    b.ToTable("second_layers_a");
                });

            modelBuilder.Entity("include_sample.Models.SecondLayerB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("FirstLayerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FirstLayerId");

                    b.ToTable("second_layers_b");
                });

            modelBuilder.Entity("include_sample.Models.ThirdLayerA", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("SecondLayerAId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SecondLayerAId");

                    b.ToTable("third_layers_a");
                });

            modelBuilder.Entity("include_sample.Models.ThirdLayerB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("SecondLayerBId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SecondLayerBId");

                    b.ToTable("third_layers_b");
                });

            modelBuilder.Entity("include_sample.Models.SecondLayerA", b =>
                {
                    b.HasOne("include_sample.Models.FirstLayer", "FirstLayer")
                        .WithMany("SecondLayersA")
                        .HasForeignKey("FirstLayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FirstLayer");
                });

            modelBuilder.Entity("include_sample.Models.SecondLayerB", b =>
                {
                    b.HasOne("include_sample.Models.FirstLayer", "FirstLayer")
                        .WithMany("SecondLayersB")
                        .HasForeignKey("FirstLayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FirstLayer");
                });

            modelBuilder.Entity("include_sample.Models.ThirdLayerA", b =>
                {
                    b.HasOne("include_sample.Models.SecondLayerA", "SecondLayerA")
                        .WithMany("ThirdLayers")
                        .HasForeignKey("SecondLayerAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SecondLayerA");
                });

            modelBuilder.Entity("include_sample.Models.ThirdLayerB", b =>
                {
                    b.HasOne("include_sample.Models.SecondLayerB", "SecondLayerB")
                        .WithMany("ThirdLayers")
                        .HasForeignKey("SecondLayerBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SecondLayerB");
                });

            modelBuilder.Entity("include_sample.Models.FirstLayer", b =>
                {
                    b.Navigation("SecondLayersA");

                    b.Navigation("SecondLayersB");
                });

            modelBuilder.Entity("include_sample.Models.SecondLayerA", b =>
                {
                    b.Navigation("ThirdLayers");
                });

            modelBuilder.Entity("include_sample.Models.SecondLayerB", b =>
                {
                    b.Navigation("ThirdLayers");
                });
#pragma warning restore 612, 618
        }
    }
}
