// <auto-generated />
using JuniorTennis.Infrastructure.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace include_sample.Migrations
{
    [DbContext(typeof(SampleDbContext))]
    partial class SampleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("include_sample.Models.FirstLayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.HasKey("Id");

                    b.ToTable("first_layers");
                });

            modelBuilder.Entity("include_sample.Models.FourthLayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("ThirdLayerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ThirdLayerId");

                    b.ToTable("fourth_layers");
                });

            modelBuilder.Entity("include_sample.Models.SecondLayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("FirstLayerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FirstLayerId");

                    b.ToTable("second_layers");
                });

            modelBuilder.Entity("include_sample.Models.ThirdLayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("SecondLayerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SecondLayerId");

                    b.ToTable("third_layers");
                });

            modelBuilder.Entity("include_sample.Models.FourthLayer", b =>
                {
                    b.HasOne("include_sample.Models.ThirdLayer", "ThirdLayer")
                        .WithMany("FourthLayers")
                        .HasForeignKey("ThirdLayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ThirdLayer");
                });

            modelBuilder.Entity("include_sample.Models.SecondLayer", b =>
                {
                    b.HasOne("include_sample.Models.FirstLayer", "FirstLayer")
                        .WithMany("SecondLayers")
                        .HasForeignKey("FirstLayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FirstLayer");
                });

            modelBuilder.Entity("include_sample.Models.ThirdLayer", b =>
                {
                    b.HasOne("include_sample.Models.SecondLayer", "SecondLayer")
                        .WithMany("ThirdLayers")
                        .HasForeignKey("SecondLayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SecondLayer");
                });

            modelBuilder.Entity("include_sample.Models.FirstLayer", b =>
                {
                    b.Navigation("SecondLayers");
                });

            modelBuilder.Entity("include_sample.Models.SecondLayer", b =>
                {
                    b.Navigation("ThirdLayers");
                });

            modelBuilder.Entity("include_sample.Models.ThirdLayer", b =>
                {
                    b.Navigation("FourthLayers");
                });
#pragma warning restore 612, 618
        }
    }
}
